{
  "openapi": "3.1.0",
  "info": {
    "version": "v1",
    "title": "Knowledge Base APIs",
    "description": "APIs for managing documents in the Knowledge Base, including uploading, deleting, retrieving, and replacing documents of various types (pdf, text, docx, url, table).\n"
  },
  "tags": [
    {
      "name": "API Reference"
    }
  ],
  "servers": [
    {
      "url": "https://api.voiceflow.com"
    }
  ],
  "x-readme": {
    "explorer-enabled": true,
    "proxy-enabled": true,
    "samples-enabled": true
  },
  "paths": {
    "/v1/knowledge-base/docs/upload": {
      "parameters": [
        {
          "name": "overwrite",
          "in": "query",
          "description": "Specify whether to overwrite existing data (optional). \"True\" means you want to overwrite.",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "maxChunkSize",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/maxChunkSize"
          }
        },
        {
          "name": "tags",
          "in": "query",
          "description": "An array of tag labels to attach to a KB document that can be used to filter document eligibility in query retrieval (i.e. tags=label1&tags=label2 or you can use tags=[\"label1\",\"label2\"]).\n",
          "required": false,
          "style": "form",
          "explode": true,
          "schema": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        {
          "name": "markdownConversion",
          "in": "query",
          "description": "Part of a beta for smart chunking where we will be doing automatic HTML to markdown conversion for the purposes of generating better chunks. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmGeneratedQ",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a question based on the document context and specific chunk, and prepend it to the chunk. This enhances retrieval by aligning chunks with potential user queries. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmPrependContext",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a context summary based on the document and chunk context, and prepend it to each chunk. This improves retrieval by providing additional context to each chunk. **Note:** If both llmGeneratedQ and llmPrependContext are set to true, llmGeneratedQ takes precedence, and the context summarization will not be applied. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmBasedChunks",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to determine the optimal chunking of the document content based on semantic similarity and retrieval effectiveness. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmContentSummarization",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to summarize and rewrite the content, removing unnecessary information and focusing on important parts to optimize for retrieval. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        }
      ],
      "post": {
        "summary": "Upload Document (File)",
        "description": "Uploads a document to the Knowledge Base. Supports uploading documents of types \"pdf\", \"text\", \"docx\" via multipart/form-data. Limit is one document per call.\n",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary",
                    "description": "The file for document types pdf, text, and docx. Limit is one file per call.\n"
                  },
                  "metadata": {
                    "type": "string",
                    "description": "Custom key-value pairs metadata to be included with the file upload. Format: --form metadata:{\"key\":\"value\"}. [Learn more](https://developer.voiceflow.com/docs/filter-with-metadata)\n"
                  }
                },
                "required": [
                  "file"
                ]
              },
              "encoding": {
                "metadata": {
                  "contentType": "application/json"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Document"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/knowledge-base/docs/upload/url": {
      "parameters": [
        {
          "name": "overwrite",
          "in": "query",
          "description": "Specify whether to overwrite existing data (optional). \"True\" means you want to overwrite.",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "maxChunkSize",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/maxChunkSize"
          }
        },
        {
          "name": "tags",
          "in": "query",
          "description": "An array of tag labels to attach to a KB document that can be used to filter document eligibility in query retrieval (i.e. tags=label1&tags=label2 or you can use tags=[\"label1\",\"label2\"]).\n",
          "required": false,
          "style": "form",
          "explode": true,
          "schema": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        {
          "name": "markdownConversion",
          "in": "query",
          "description": "Part of a beta for smart chunking where we will be doing automatic HTML to markdown conversion for the purposes of generating better chunks. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmGeneratedQ",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a question based on the document context and specific chunk, and prepend it to the chunk. This enhances retrieval by aligning chunks with potential user queries. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmPrependContext",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a context summary based on the document and chunk context, and prepend it to each chunk. This improves retrieval by providing additional context to each chunk. **Note:** If both llmGeneratedQ and llmPrependContext are set to true, llmGeneratedQ takes precedence, and the context summarization will not be applied. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmBasedChunks",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to determine the optimal chunking of the document content based on semantic similarity and retrieval effectiveness. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmContentSummarization",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to summarize and rewrite the content, removing unnecessary information and focusing on important parts to optimize for retrieval. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        }
      ],
      "post": {
        "summary": "Upload Document (URL)",
        "description": "Uploads a document of type \"url\" to the Knowledge Base. Limit is one URL per call.\n",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DocumentDataUrl"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Document"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/knowledge-base/docs/{documentID}": {
      "parameters": [
        {
          "name": "documentID",
          "in": "path",
          "required": true,
          "description": "A unique identifier of the document object.",
          "schema": {
            "type": "string"
          }
        }
      ],
      "delete": {
        "summary": "Delete Document",
        "description": "Deletes a specific Knowledge Base document by documentID.",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response with no content."
          }
        }
      },
      "get": {
        "summary": "Document Chunk Retrieval",
        "description": "Retrieves the chunks for a Knowledge Base doc by documentID.",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Document"
                      }
                    },
                    "chunks": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Chunks"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/knowledge-base/docs": {
      "parameters": [
        {
          "name": "page",
          "in": "query",
          "description": "Optional pagination parameter - The page number to retrieve, defaults to 1 (which is the minimum). Order is by the date updated, descending.\n",
          "schema": {
            "type": "integer",
            "default": 1
          }
        },
        {
          "name": "limit",
          "in": "query",
          "description": "Optional pagination parameter - the number of documents to return per page. Defaults to 10, range is 1-100.\n",
          "schema": {
            "type": "integer",
            "default": 10
          }
        },
        {
          "name": "documentType",
          "in": "query",
          "description": "Optional pagination parameter - Filters the document list by type (url, pdf, text, docx, table). Defaults to all document types.\n",
          "schema": {
            "type": "string",
            "enum": [
              "url",
              "pdf",
              "text",
              "docx",
              "table"
            ]
          }
        },
        {
          "name": "includeTags",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/IncludeTags"
          }
        },
        {
          "name": "includeAllNonTagged",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/IncludeAllNonTagged"
          }
        },
        {
          "name": "includeAllTagged",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/IncludeAllTagged"
          }
        },
        {
          "name": "excludeTags",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/ExcludeTags"
          }
        }
      ],
      "get": {
        "summary": "Document List",
        "description": "Retrieves a list of all documents within a given project's Knowledge Base.\n",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "total": {
                      "type": "integer",
                      "description": "Total number of Knowledge Base documents."
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Document"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/knowledge-base/docs/{documentID}/upload": {
      "parameters": [
        {
          "name": "documentID",
          "in": "path",
          "required": true,
          "description": "A unique identifier of the document object.",
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "maxChunkSize",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/maxChunkSize"
          }
        },
        {
          "name": "markdownConversion",
          "in": "query",
          "description": "Part of a beta for smart chunking where we will be doing automatic HTML to markdown conversion for the purposes of generating better chunks. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmGeneratedQ",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a question based on the document context and specific chunk, and prepend it to the chunk. This enhances retrieval by aligning chunks with potential user queries. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmPrependContext",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a context summary based on the document and chunk context, and prepend it to each chunk. This improves retrieval by providing additional context to each chunk. **Note:** If both llmGeneratedQ and llmPrependContext are set to true, llmGeneratedQ takes precedence, and the context summarization will not be applied. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmBasedChunks",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to determine the optimal chunking of the document content based on semantic similarity and retrieval effectiveness. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmContentSummarization",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to summarize and rewrite the content, removing unnecessary information and focusing on important parts to optimize for retrieval. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        }
      ],
      "put": {
        "summary": "Replace Document (File)",
        "description": "Replaces the document and document name in the Knowledge Base, by documentID. Supports replacing documents of types \"pdf\", \"text\", \"docx\" via multipart/form-data. Limit one per call.\n",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary",
                    "description": "The file for document types pdf, text, and docx. Limit is one file per call.\n"
                  },
                  "metadata": {
                    "type": "string",
                    "description": "Custom key-value pairs metadata to be included with the file upload. Format: --form metadata:{\"key\":\"value\"}. [Learn more](https://developer.voiceflow.com/docs/filter-with-metadata)\n"
                  }
                },
                "required": [
                  "file"
                ]
              },
              "encoding": {
                "metadata": {
                  "contentType": "application/json"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Document"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/knowledge-base/docs/{documentID}/upload/url": {
      "parameters": [
        {
          "name": "documentID",
          "in": "path",
          "required": true,
          "description": "A unique identifier of the document object.",
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "maxChunkSize",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/maxChunkSize"
          }
        },
        {
          "name": "markdownConversion",
          "in": "query",
          "description": "Part of a beta for smart chunking where we will be doing automatic HTML to markdown conversion for the purposes of generating better chunks. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmGeneratedQ",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a question based on the document context and specific chunk, and prepend it to the chunk. This enhances retrieval by aligning chunks with potential user queries. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmPrependContext",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to generate a context summary based on the document and chunk context, and prepend it to each chunk. This improves retrieval by providing additional context to each chunk. **Note:** If both llmGeneratedQ and llmPrependContext are set to true, llmGeneratedQ takes precedence, and the context summarization will not be applied. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmBasedChunks",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to determine the optimal chunking of the document content based on semantic similarity and retrieval effectiveness. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        },
        {
          "name": "llmContentSummarization",
          "in": "query",
          "description": "Part of a beta for smart chunking where we use an LLM to summarize and rewrite the content, removing unnecessary information and focusing on important parts to optimize for retrieval. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
          "schema": {
            "type": "boolean"
          }
        }
      ],
      "put": {
        "summary": "Replace Document (URL)",
        "description": "Replaces the document and document name in the Knowledge Base, by documentID (of type \"url\" only). Limit one per call.\n",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DocumentDataUrl"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Document"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/knowledge-base/docs/upload/table": {
      "post": {
        "summary": "Upload Table Data",
        "description": "Uploads new table data to the Knowledge Base. This endpoint supports completely custom fields in the table data, including various data types such as string, number, array, or object.\n",
        "tags": [
          "API Reference"
        ],
        "security": [
          {
            "DialogManagerAPIKey": []
          }
        ],
        "parameters": [
          {
            "name": "overwrite",
            "in": "query",
            "required": false,
            "description": "If set to true, the existing table with the same name will be overwritten.\n",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "markdownConversion",
            "in": "query",
            "required": false,
            "description": "Part of a beta for smart chunking where we will be doing automatic HTML to markdown conversion for the purposes of generating better chunks. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "llmGeneratedQ",
            "in": "query",
            "required": false,
            "description": "Part of a beta for smart chunking where we use an LLM to generate a question based on the document context and specific chunk, and prepend it to the chunk. This enhances retrieval by aligning chunks with potential user queries. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "llmPrependContext",
            "in": "query",
            "required": false,
            "description": "Part of a beta for smart chunking where we use an LLM to generate a context summary based on the document and chunk context, and prepend it to each chunk. This improves retrieval by providing additional context to each chunk. **Note:** If both llmGeneratedQ and llmPrependContext are set to true, llmGeneratedQ takes precedence, and the context summarization will not be applied. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "llmContentSummarization",
            "in": "query",
            "required": false,
            "description": "Part of a beta for smart chunking where we use an LLM to summarize and rewrite the content, removing unnecessary information and focusing on important parts to optimize for retrieval. **Limited to 15 rows per table upload**. [Join the waiting list](https://beta.proxy-voiceflow.com/?beta=smartchunking)\n",
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "data"
                ],
                "properties": {
                  "data": {
                    "type": "object",
                    "required": [
                      "name",
                      "schema",
                      "items"
                    ],
                    "properties": {
                      "name": {
                        "type": "string",
                        "description": "A unique name identifying the table."
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "searchableFields": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            },
                            "description": "An array of fields within each item that can be searched. Only supports fields of type string, number, or boolean. Does not support fields of type array or object.\n"
                          },
                          "metadataFields": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            },
                            "description": "An array of fields within each item that are considered metadata for additional context. You can filter by metadata fields. This field is optional. [Learn more](https://developer.voiceflow.com/docs/filter-with-metadata)\n"
                          }
                        }
                      },
                      "items": {
                        "type": "array",
                        "description": "An array of items to be included in the table. Each item can have completely custom fields of various types including string, number, array, or object.\n",
                        "items": {
                          "type": "object",
                          "additionalProperties": {
                            "oneOf": [
                              {
                                "type": "string"
                              },
                              {
                                "type": "number"
                              },
                              {
                                "type": "array",
                                "items": {}
                              },
                              {
                                "type": "object"
                              }
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              },
              "example": {
                "data": {
                  "name": "products",
                  "schema": {
                    "searchableFields": [
                      "name",
                      "description"
                    ],
                    "metadataFields": [
                      "description",
                      "price",
                      "inventory_count"
                    ]
                  },
                  "items": [
                    {
                      "id": 1,
                      "name": "Ultimate Glow Kit",
                      "description": "A complete kit for achieving the ultimate skin glow, including serum, moisturizer, and face mask.\n",
                      "price": 120.99,
                      "inventory_count": 150
                    },
                    {
                      "id": 2,
                      "name": "Hydration Sensation Kit",
                      "description": "The ultimate hydration kit, including a water-based serum, hydrating cream, and a deep moisture mask.\n",
                      "price": 99.99,
                      "inventory_count": 200
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "object",
                          "properties": {
                            "name": {
                              "type": "string"
                            },
                            "type": {
                              "type": "string"
                            },
                            "rowsCount": {
                              "type": "integer"
                            }
                          }
                        },
                        "documentID": {
                          "type": "string"
                        },
                        "updatedAt": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "status": {
                          "type": "object",
                          "properties": {
                            "type": {
                              "type": "string"
                            }
                          }
                        },
                        "tags": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "data": {
                      "data": {
                        "name": "products",
                        "type": "table",
                        "rowsCount": 4
                      },
                      "documentID": "66821ba553dbbb191a23b21c",
                      "updatedAt": "2024-07-02T13:52:15.809Z",
                      "status": {
                        "type": "PENDING"
                      },
                      "tags": []
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - The request was invalid. This can occur due to various reasons such as poorly formatted request body, missing required fields, invalid data types in searchable fields, or metadata field size exceeding the limit.\n",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "integer",
                          "example": 400
                        },
                        "message": {
                          "type": "string"
                        },
                        "details": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "examples": {
                    "PoorlyFormattedRequest": {
                      "summary": "Poorly Formatted Request Body",
                      "value": {
                        "error": {
                          "code": 400,
                          "message": "Invalid Request Format",
                          "details": "The request body is poorly formatted. Please ensure the request follows the correct JSON structure and includes all required fields.\n"
                        }
                      }
                    },
                    "MissingRequiredFields": {
                      "summary": "Missing Required Fields",
                      "value": {
                        "error": {
                          "code": 400,
                          "message": "Missing Required Fields",
                          "details": "The request body is missing required fields. Please ensure all required fields are included.\n"
                        }
                      }
                    },
                    "ComplexTypeInSearchableField": {
                      "summary": "Complex Type in Searchable Field",
                      "value": {
                        "error": {
                          "code": 400,
                          "message": "Invalid Searchable Field",
                          "details": "Complex types are not allowed in searchable fields. Please use a supported data type.\n"
                        }
                      }
                    },
                    "MetadataFieldSize": {
                      "summary": "Metadata Field Size Exceeded",
                      "value": {
                        "error": {
                          "code": 400,
                          "message": "Metadata Field Size Exceeded",
                          "details": "The request metadata field must be less than 10 KB.\n"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - The request was understood, but it has been refused or access is not allowed. This can occur if the number of rows in the uploaded table exceeds the limit for your current plan.\n",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "integer",
                          "example": 403
                        },
                        "message": {
                          "type": "string"
                        },
                        "details": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": {
                    "code": 403,
                    "message": "Row Limit Exceeded",
                    "details": "The number of rows in the uploaded table exceeds the limit for your current plan. Please upgrade your plan to upload tables with more rows.\n"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity - The request was well-formed but was unable to be followed due to semantic errors. This can occur if the metadata format is invalid.\n",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "integer",
                          "example": 422
                        },
                        "message": {
                          "type": "string"
                        },
                        "details": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": {
                    "code": 422,
                    "message": "Invalid Metadata Format",
                    "details": "The metadata format is invalid. Please ensure the metadata adheres to the required schema.\n"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Document": {
        "type": "object",
        "properties": {
          "status": {
            "$ref": "#/components/schemas/DocumentStatus"
          },
          "data": {
            "$ref": "#/components/schemas/DocumentData"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          },
          "documentID": {
            "type": "string",
            "description": "A unique identifier of the document object."
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "An array of tag labels associated with the document."
          }
        }
      },
      "DocumentStatus": {
        "type": "string",
        "enum": [
          "ERROR",
          "SUCCESS",
          "PENDING",
          "INITIALIZED"
        ]
      },
      "DocumentData": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "url",
              "pdf",
              "text",
              "docx",
              "table"
            ],
            "description": "The type of the source document (url, pdf, text, docx, table).\n"
          },
          "name": {
            "type": "string",
            "description": "A readable name for the document."
          },
          "url": {
            "type": "string",
            "description": "The URL for documents of type \"url\" only."
          },
          "metadata": {
            "type": "object",
            "additionalProperties": true,
            "description": "A metadata object to attach additional information to the document. [Learn more](https://developer.voiceflow.com/docs/filter-with-metadata)\n"
          },
          "rowsCount": {
            "type": "integer",
            "description": "Number of rows in the table document (for documents of type \"table\" only).\n"
          }
        }
      },
      "DocumentDataUrl": {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "url"
                ],
                "default": "url",
                "description": "The type of the source document (url). Limit is one URL per call.\n"
              },
              "url": {
                "type": "string",
                "description": "The URL for documents of type \"url\". Limit is one URL per call.\n"
              },
              "metadata": {
                "type": "object",
                "additionalProperties": true,
                "description": "A metadata object to attach additional information to the document.\n"
              }
            }
          }
        }
      },
      "Chunks": {
        "type": "object",
        "properties": {
          "chunkID": {
            "type": "integer",
            "description": "The unique identifier of the chunk. A chunk is a section of text."
          },
          "content": {
            "type": "string",
            "description": "The actual content of the chunk."
          }
        }
      },
      "maxChunkSize": {
        "type": "integer",
        "default": 1000,
        "description": "Optional - Determines how granularly each document is broken up. Range available is 500-1500 tokens, default is 1000. Smaller chunk size means narrower context, faster response, less tokens consumed, and greater risk of less accurate answers. Max chunk size affects the total amount of chunks parsed from a document - i.e., larger chunks means less chunks retrieved.\n"
      },
      "IncludeTags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "An array of KB tag labels to filter documents by."
      },
      "IncludeAllNonTagged": {
        "type": "boolean",
        "description": "Include documents without KB tags."
      },
      "IncludeAllTagged": {
        "type": "boolean",
        "description": "Include all documents with KB tags."
      },
      "ExcludeTags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "An array of KB tag labels to exclude documents."
      }
    },
    "securitySchemes": {
      "DialogManagerAPIKey": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "description": "All requests made to any Knowledge Base APIs must be validated with a Dialog Manager API Key.\n\nTo obtain a Dialog Manager API key, go to the Integration tab on the project you uploaded data sources to and click the \"Copy API key\" button.\n"
      }
    }
  }
}